name = "premium-final-proxy"
type = "webpack" # or "javascript"
account_id = "253abf5d75d04f703528a62fe63dad59"

[site]
bucket = "./"  # point to the root folder containing your static files
entry-point = "workers-site"
