name = "premium-final-proxy"
type = "webpack" # or "javascript"
account_id = "253abf5d75d04f703528a62fe63dad59"
workers_dev = true

[site]
bucket = "./public"  # folder containing your static files
entry-point = "workers-site"
